[LM-10923] Added API Key Security
LikeMindsCommunity/likeminds-chat-android-community-archV1 pull request #37
Opened 2024-07-23 10:03 UTC by ishaan1607

## Description

**Features**
- Added API Key Security

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [x] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [x] Label added
- [x] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [x] Description about the Feature/ Bugs added

2024-07-29 14:50 UTC, sidcr7-likeminds commented on app/src/main/java/com/likeminds/chatsampleapp/GetTokensTask.kt
> +                "https://betaauth.likeminds.community/sdk/initiate"
store these values in `BuildConfig`

2024-07-29 15:01 UTC, sidcr7-likeminds requested changes

2024-07-29 15:01 UTC, sidcr7-likeminds commented on chatmm/src/main/java/com/likeminds/chatmm/member/util/UserResponseConvertor.kt
> +}
Can write this in `ViewDataonverter.kt`

2024-07-29 15:01 UTC, sidcr7-likeminds commented on chatmm/src/main/java/com/likeminds/chatmm/utils/user/LMChatUserMetaData.kt
> +    fun init(
add comments

2024-07-29 15:01 UTC, sidcr7-likeminds commented on chatmm/src/main/java/com/likeminds/chatmm/utils/user/LMChatUserMetaData.kt
> +    fun onPostUserSessionInit(
add comments

2024-07-29 15:01 UTC, sidcr7-likeminds commented on chatmm/src/main/java/com/likeminds/chatmm/utils/user/LMChatUserMetaData.kt
> +    private fun registerDevice(token: String) {
add comments

2024-07-30 05:30 UTC, ishaan1607 commented on app/src/main/java/com/likeminds/chatsampleapp/GetTokensTask.kt
> +                "https://betaauth.likeminds.community/sdk/initiate"
These are example code, not necessaey

2024-07-30 06:19 UTC, sidcr7-likeminds approved these changes

2024-07-30 06:22 UTC, merged