[LM-13201] Migrate targetSdk to version 35
LikeMindsCommunity/likeminds-chat-android-community-archV1 pull request #64
Opened 2024-12-16 14:44 UTC by sidcr7-likeminds

## Description

**Features**

- Migrated targetSdk version to 35
- Upgraded Gradle version
- Upgraded Android Gradle Plugin version
- Upgraded Kotlin version

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2024-12-16 16:04 UTC, ishaan1607 requested changes

2024-12-16 16:04 UTC, ishaan1607 commented on chatmm/src/main/java/com/likeminds/chatmm/reactions/view/ReactionsListDialog.kt
> +                            "$reaction ${reactionsHashmap[listOfReactions[pos - 1]]?.size}"
revert this changes

2024-12-16 16:04 UTC, ishaan1607 commented on chatmm/src/main/java/com/likeminds/chatmm/utils/Route.kt
> +        data?.host ?: return null
revert this

2024-12-16 16:22 UTC, sidcr7-likeminds commented on chatmm/src/main/AndroidManifest.xml
> -        tools:ignore="ScopedStorage" />
Because it was duplicate and was giving a warning

2025-01-07 04:25 UTC, ishaan1607 requested changes

2025-01-07 04:25 UTC, ishaan1607 commented on chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
Check the imports statement setting

2025-01-07 04:25 UTC, ishaan1607 commented on chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
> +            }
why this check is necessary?

2025-01-07 04:25 UTC, ishaan1607 commented on chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
> +            )
remove logs

2025-01-07 04:25 UTC, ishaan1607 commented on chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
> +                        Log.d("PUI", "Dates: ${it.date}")
remove logs

2025-01-07 04:25 UTC, ishaan1607 commented on chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
> +                    }
remove logs

2025-01-07 04:25 UTC, ishaan1607 commented on chatmm/src/main/java/com/likeminds/chatmm/conversation/util/ChatReplyUtil.kt
check import statement setting, all import statement are opened

2025-01-08 10:23 UTC, ishaan1607 approved these changes

2025-01-08 10:45 UTC, merged